development:
  adapter: postgresql
  database: scratch_golfer_v2_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: scratch_golfer_v2_test
  pool: 5
  timeout: 5000
production: 
  adapter: postgresql
  database: scratch_golfer_v2_production
  pool: 5
  timeout: 5000
